// apps/admin/src/components/Login.svelte
<script lang="ts">
  import type { CurrentUser } from '@turmstatus/shared';
  import { apiPost, ApiError } from '../lib/api.js';
  import { currentUser, showToast } from '../lib/stores.js';

  let username = '';
  let password = '';
  let busy = false;

  async function submit() {
    busy = true;
    try {
      const res = await apiPost<{ user: CurrentUser }>('/api/auth/login', { username, password });
      if (!res.user.isAdmin) {
        showToast('Kein Administrator-Konto', 'error');
        currentUser.set(null);
        return;
      }
      currentUser.set(res.user);
    } catch (err) {
      showToast(err instanceof ApiError ? err.message : 'Anmeldung fehlgeschlagen', 'error');
    } finally {
      busy = false;
    }
  }
</script>

<div class="center-screen">
  <div class="modal" style="max-width: 360px;">
    <h3 style="color: var(--sea-bright);">Turmstatus · Administration</h3>
    <p class="muted small">Interner Admin-Bereich (nur im lokalen Netz erreichbar).</p>
    <form on:submit|preventDefault={submit}>
      <div class="field"><label for="u">Benutzername</label><input id="u" bind:value={username} required /></div>
      <div class="field"><label for="p">Passwort</label><input id="p" type="password" bind:value={password} required /></div>
      <button class="primary" style="width:100%;" disabled={busy}>Anmelden</button>
    </form>
  </div>
</div>

// frontend/src/pages/Login.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { login } from "../api";
import { useStore } from "../store";

export default function Login() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const navigate = useNavigate();
  const { loadMe, refreshAll } = useStore();

  const submit = async (e) => {
    e.preventDefault();
    setError("");
    setBusy(true);
    try {
      await login(username, password);
      await loadMe();
      await refreshAll();
      navigate("/");
    } catch (err) {
      setError(err.response?.data?.detail || "Anmeldung fehlgeschlagen");
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="login-wrap">
      <form className="login-card" onSubmit={submit}>
        <h1>🛟 Turmstatus</h1>
        <div className="sub">Wach- und Statussystem Wasserrettung</div>
        <div className="field">
          <label>Benutzername</label>
          <input value={username} onChange={(e) => setUsername(e.target.value)} autoFocus />
        </div>
        <div className="field">
          <label>Passwort</label>
          <input type="password" value={password} onChange={(e) => setPassword(e.target.value)} />
        </div>
        {error && <div className="error">{error}</div>}
        <button className="btn btn-primary btn-block" disabled={busy}>
          {busy ? "Anmelden…" : "Anmelden"}
        </button>
      </form>
    </div>
  );
}
